# Generated by Django 5.0.1 on 2024-06-29 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_title",
                    models.CharField(max_length=200, verbose_name="Название статьи"),
                ),
                ("article_text", models.TextField(verbose_name="Текст статьи")),
                ("pub_date", models.DateTimeField(verbose_name="Дата публикации")),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name",
                    models.CharField(max_length=50, verbose_name="Имя автора"),
                ),
                (
                    "comment_text",
                    models.CharField(max_length=200, verbose_name="Текст комментария"),
                ),
                (
                    "arcticle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
            ],
        ),
    ]
